### ISSUE TITLE
Use JSON parser for Booking retrive Validations.

### ISSUE THREAD

**Issue by jetsasank** [ZapcgInc/Hopper_Dev#4]
For consistency and better code lets use Parsed JSON response for validations. Using parsed JSON response will
1. Makes the business logic readable.
2. Avoids multiple parsing of JSON string for each validation method.  

This has been the case  for all other response types.
https://github.com/ZapcgInc/Hopper_Dev/blob/481e00e11f918fb159b160a18136cbf6683bb37f/testsuit_eps_rapid/src/test/java/com/hopper/tests/validations/retrievebooking/RetrieveBookingValidation.java#L124

cc : @niobuddy @dpuranam

**Comment by jayeesmaZapCg** [comment]
I did that previously, but that involved creating some new pojos for rooms and rates. But since the testcases were pretty straight forward, Srinivas suggested to with the present implementation.

**Comment by niobuddy** [comment]
Teja,

For this requirement easy to validate using JSON path supported by RestAssured library.  Creating Pojo and adding a validation will be tricky and time consuming process. For testsuite unless really needed no need to create pojo’s for every small validation.

-Srinivas
