### ISSUE TITLE
Delete or Refactor the validation

### ISSUE THREAD

**Issue by gorthitk** [ZapcgInc/Hopper_Dev#7]
The test case name here refers to a very specific location : "Paris". The test suite should be more generalized. I suggest two things :
1. Delete this test case.
2. Add a another test case for validating the fields in a more generic way. 

https://github.com/ZapcgInc/Hopper_Dev/blob/481e00e11f918fb159b160a18136cbf6683bb37f/testsuit_eps_rapid/src/test/java/com/hopper/tests/definitions/GlobalTestScenarioDefinitions.java#L213-L228

cc : @niobuddy @dpuranam

**Comment by jayeesmaZapCg** [comment]
Refactored.
